config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'varieties/popular', to: 'varieties#popular'
  
  resources :varieties
  resources :wines do
    resources :reviews, only: [:index, :show, :new]
  end
  resources :reviews
  resources :users do
    resources :reviews, only: [:index, :show]
  end

  root 'application#root'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')


end

app/models/variety.rb
class Variety < ApplicationRecord
  validates :color, presence: true
  validates :name, presence: true

  has_many :wines

 #  scope :red, -> { where(color: 'red') }
 #  scope :white, -> { where(color: 'white') }
 #  scope :pink, -> { where(color: 'pink') }

  scope :selected_color, -> (color) { where(color: color) }

  scope :popular, -> { joins(:wines).group(:variety_id).order("count(wines.id) DESC").limit(1)}
end

app/controllers/varieties_controller.rb
class VarietiesController < ApplicationController
  before_action :require_login
  before_action :admin_only, only: [:edit, :update, :destroy]

  def popular
    @variety = Variety.popular.first
    # render 'varieties/popular'
  end

  def index
    @varieties = Variety.all
  end

  def show
    if params[:id] == "red" || params[:id] == "white" || params[:id] == "pink"
      @varieties = Variety.selected_color(params[:id])
      render 'varieties/index'
    else
      @variety = Variety.find(params[:id])
      @wines = Wine.by_variety(@variety)
    end
  end

  def new
    @variety = Variety.new
  end

  def edit
    @variety = Variety.find(params[:id])
  end

  def create
    @variety = Variety.new(variety_params)
    if @variety.save
      redirect_to variety_path(@variety)
    else
      @varieties = Variety.all
      render 'varieties/new'
    end
  end

  def update
    @variety = Variety.find(params[:id])
    @variety.update(variety_params)
    if @variety.save
      redirect_to variety_path(@variety)
    else
      render 'variety/edit'
    end
  end

  def destroy
    @variety = Variety.find(params[:id])
    @variety.destroy
    redirect_to varieties_path
  end

  private

  def variety_params
    params.require(:variety).permit(:name, :color)
  end
end

app/helpers/varieties_helper.rb
module VarietiesHelper
end

app/views/varieties/_form.html.erb
<% if !@variety.errors.empty? %>
  <% @variety.errors.full_messages.each do |error_message| %>
    <p class="error"><%= error_message %></p>
  <% end %>
<% end %>
<%= form_for @variety do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br />
  <%= f.label :color %>
  <%= f.text_field :color %><br />
  <%= f.submit %>
<% end %>

app/views/varieties/edit.html.erb
<h1>Edit Variety - <%= @variety.name %>:</h1>

<%= render "form" %>

app/views/varieties/index.html.erb
<h1>Varieties:</h1>
<div class="main_content">
  <ul>
    <% @varieties.each do |variety| %>
      <li><%= link_to variety.name, variety_path(variety) %></li>
    <% end %>
  </ul>
</div>

app/views/varieties/new.html.erb
<h1>New Variety:</h1>

<%= render "form" %>

app/views/varieties/popular.html.erb
<%= @variety.name %>

app/views/varieties/show.html.erb
<h1><%= @variety.name %></h1>
<p>Color: <%= @variety.color %></p>
<p>Wines:</p>
<div class="main_content">
  <ul>
    <% @wines.each do |wine| %>
      <li><%= link_to "#{wine.name} - #{wine.average_rating} stars", wine_path(wine) %></li>
    <% end %>
  </ul>
</div>
<% if current_user.admin %>
  <div class="btn">
    <%= link_to "Edit Variety", edit_variety_path(@variety) %>
  </div>
  <div class="btn">
    <%= link_to "Delete Variety", variety_path(@variety), method: "PATCH" %>
  </div>
<% end %>
<div class="btn"><%= link_to "Back to Wine List", wines_path %></div><br />