config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'varieties/popular', to: 'varieties#popular'
  
  resources :varieties
  resources :wines do
    resources :reviews, only: [:index, :show, :new]
  end
  resources :reviews
  resources :users do
    resources :reviews, only: [:index, :show]
  end

  root 'application#root'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')


end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true

  has_many :reviews
  has_many :wines, through: :reviews

  def self.from_omniauth(auth)
    # Creates a new user only if it doesn't exist
    where(username: auth.info.email).first_or_initialize do |user|
      user.username = auth.info.email.split("@").first
      user.password ||= SecureRandom.hex
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action: admin_only, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params(:username, :password))
    if @user.save
      session[:user_id] = @user.id
      redirect_to wines_path
    else
      render new_user_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params(:username, :password, :admin))
    if @user.save?
      redirect_to user_path(@user)
    else
      render 'user/edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.reviews.each { |review| review.destroy }
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params(* args)
    params.require(:user).permit(args)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if !@user.errors.empty? %>
  <% @user.errors.full_messages.each do |error_message| %>
    <p class="error"><%= error_message %></p>
  <% end %>
<% end %>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br />
  <%= f.label :password %>
  <%= f.password_field :password %></br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></br />
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User:</h1>

<%= render "form" %>

app/views/users/index.html.erb
<h1>Users:</h1>
<div class="big_content">
  <% @users.each do |user| %>
    <p><%= link_to user.username, user_reviews_path(user) %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>New User:</h1>
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br />
  <%= f.label :password %>
  <%= f.password_field :password %></br />
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %></br />
  <%= f.submit "Create User" %>
<% end %>