config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'varieties/popular', to: 'varieties#popular'
  
  resources :varieties
  resources :wines do
    resources :reviews, only: [:index, :show, :new]
  end
  resources :reviews
  resources :users do
    resources :reviews, only: [:index, :show]
  end

  root 'application#root'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def root
  end

  helper_method :current_user, :log_in, :logged_in?

  def current_user
    if session[:user_id]
      if session[:user_id]
        @current_user ||= User.find(session[:user_id])
      end
    end
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    @logged_in = !!current_user
  end

  def require_login
    unless logged_in?
      flash[:error] = "Please log in to access the application"
      redirect_to root_path
    end
  end

  def logout
    session.clear
    redirect_to root_path
  end

  def admin_only
    redirect_to root_path if !current_user.admin
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/root.html.erb
<h1>Welcome to Somm<h1>
<%= form_tag(new_user_path, method: "GET") do %>
  <%= submit_tag "Create New User" %><br />
<% end %>
<%= form_tag login_path, method: "GET" do %>
  <%= submit_tag "Login Existing User" %><br />
<% end %>
<%= form_tag '/auth/google_oauth2', method: "GET" do %>
  <%= submit_tag "Login Via Google" %><br />
<% end %>