config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'varieties/popular', to: 'varieties#popular'
  
  resources :varieties
  resources :wines do
    resources :reviews, only: [:index, :show, :new]
  end
  resources :reviews
  resources :users do
    resources :reviews, only: [:index, :show]
  end

  root 'application#root'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')


end

app/models/wine.rb
class Wine < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  belongs_to :variety
  has_many :reviews
  has_many :wines, through: :reviews

  def variety_attributes=(attributes)
    variety = Variety.find_or_create_by(attributes)
    self.variety = variety if variety.valid?
  end

  def self.by_variety(v)
    where(variety: v)
  end

  def self.selected_color(color)
    Wine.all.select { |wine| Variety.selected_color(color).include?(wine.variety) }
  end

  

  def average_rating
    if self.reviews.count > 0
      (self.reviews.sum { |review| review.rating }.to_f / self.reviews.count).round(1).to_s + " stars"
    else
      "No Reviews"
    end
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :require_login
  before_action :admin_only, only: [:edit, :update, :destroy]

  def index
    if params[:wine_color] && params[:wine_color] != 'all'
      @wines = Wine.selected_color(params[:wine_color])
    else
      @wines = Wine.all
    end
    @wines = @wines.sort_by{ |wine| wine.average_rating }.reverse
  end

  def show
    @wine = Wine.find(params[:id])
  end

  def new
    @wine = Wine.new
    @varieties = Variety.all
    @wine.build_variety
  end

  def edit
    @wine = Wine.find(params[:id])
    @varieties = Variety.all
  end

  def create
    @wine = Wine.new(wine_params)
    if @wine.save
      redirect_to wine_path(@wine)
    else
      @varieties = Variety.all
      render 'wines/new'
    end
  end

  def update
    @wine = Wine.find(params[:id])
    @wine.update(wine_params)
    if @wine.save
      redirect_to wine_path(@wine)
    else
      render 'wine/edit'
    end
  end

  def destroy
    @wine = Wine.find(params[:id])
    @wine.reviews.each { |review| review.destroy }
    @wine.destroy
    redirect_to wines_path
  end

  private

  def wine_params
    params.require(:wine).permit(:name, :variety_id, variety_attributes: [:name, :color])
  end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<% if !@wine.errors.empty? %>
  <% @wine.errors.full_messages.each do |error_message| %>
    <p class="error"><%= error_message %></p>
  <% end %>
<% end %>
<%= form_for @wine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br />

  <%= f.label :variety_id, "Variety:" %>
  <%= f.collection_select(:variety_id, @varieties, :id, :name, include_blank: true) %> <br />

  <h3> Or add a new variety: </h3>

  <%= f.fields_for :variety do |v| %>
    <%= v.label :name %>
    <%= v.text_field :name %><br />

    <%= v.label "New Variety Color" %>
    <%= v.text_field :color %><br />
  <% end %>

  <%= f.submit %>
<% end %>

<div class="btn"><%= link_to "Back to Wine List", wines_path %></div><br />

app/views/wines/edit.html.erb
<h1>Edit Wine</h1>

<%= render "form" %>

app/views/wines/index.html.erb
<h1>Wine List:</h1>

<div class="inline">
  <%= form_tag wines_path, method: "GET" do %>
    <%= hidden_field_tag("wine_color", "red") %>
    <%= submit_tag("Reds") %>
  <% end %>
</div>

<div class="inline">
  <%= form_tag wines_path, method: "GET" do %>
    <%= hidden_field_tag("wine_color", "white") %>
    <%= submit_tag("Whites") %>
  <% end %>
</div>

<div class="inline">
  <%= form_tag wines_path, method: "GET" do %>
    <%= hidden_field_tag("wine_color", "pink") %>
    <%= submit_tag("Pinks") %>
  <% end %>
</div>

<div class="inline">
  <%= form_tag wines_path, method: "GET" do %>
    <%= hidden_field_tag("wine_color", "all") %>
    <%= submit_tag("All") %>
  <% end %>
</div>

<div class="main_content">
  <ul>
    <% @wines.each do |wine| %>
      <li><%= link_to "#{wine.name} - #{wine.average_rating}", wine_path(wine) %></li>
    <% end %>
  </ul>
</div>
<br />
<%= link_to "New Wine", new_wine_path, class: "btn" %>
<%= link_to "Write a Review", new_review_path, class: "btn" %><br />

app/views/wines/new.html.erb
<h1>New Wine:</h1>
<%= form_for @wine do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %> <br />
  <%= f.label "Variety:" %>
  <%= f.collection_select(:variety_id, @varieties, :id, :name, include_blank: true) %> <br />
  <%= f.fields_for :variety do |v| %>
    <%= v.label "New Variety" %>
    <%= v.label :name %>
    <%= v.text_field :name %><br />
    <%= v.label :color %>
    <%= v.text_field :color %><br />
  <% end %>
  <%= f.submit "Create Wine" %>
<% end %>

app/views/wines/show.html.erb
<h1><%= @wine.name %></h1>
<p>Variety: <%= link_to @wine.variety.name, variety_path(@wine.variety) %></p>
<p>Average Rating: <%= @wine.average_rating %></p>
<% if @wine.reviews.count == 0 %>
  <div class="btn"><%= link_to "Create Review", new_wine_review_path(@wine) %></div>
<% else %>
  <div class="btn"><%= link_to "Reviews", wine_reviews_path(@wine) %></div>
<% end %>
<% if current_user.admin %>
  <div class="btn"><%= link_to "Edit Wine", edit_wine_path(@wine) %></div><br />
  <div class="btn"><%= link_to "Delete Wine", wine_path(@wine), method: "DELETE" %></div><br />
<% end %>
<div class="btn"><%= link_to "Back to Wine List", wines_path %></div><br />